version: 2.1

jobs:
  test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: set env
          command: |
            echo "export GROUP=kurumai" >> $BASH_ENV
            echo "export COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            echo "export TAG=${CIRCLE_TAG}" >> $BASH_ENV
            echo "export REPO=front-end" >> $BASH_ENV
            env
      - run:
          name: make test-image deps
          command: |
            source $BASH_ENV
            make test-image deps
      - run: npm install
      #- run: make test

  push:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: set env
          command: |
            echo "export GROUP=kurumai" >> $BASH_ENV
            echo "export COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            echo "export TAG=${CIRCLE_TAG}" >> $BASH_ENV
            echo "export REPO=front-end" >> $BASH_ENV
            env
      - run:
          name: docker build
          command: |
            docker build -t ${GROUP}/front-end:${COMMIT} .
      - run:
          name: docker tag
          command: |
            docker tag ${GROUP}/${REPO}:${COMMIT} ${GROUP}/${REPO}:master-${COMMIT:0:8}
            docker tag ${GROUP}/${REPO}:${COMMIT} ${GROUP}/${REPO}:latest
      - run: 
          name: push
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
            docker push ${GROUP}/${REPO}:master-${COMMIT:0:8}
            docker push ${GROUP}/${REPO}:latest

workflows:
  test_and_deploy:
    jobs:
      - test
      - push:
          filters:
            branches:
              only: master
          requires:
            - test