version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    executor:
      name: node/default
      tag: '4.8.1'
    steps:
      - checkout
      - run: make test-image deps
      - node/install-packages
      - run: make test

workflows:
  test_and_deploy:
    jobs:
      - test