version: 2.1

jobs:
  test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: set env
          command: |
            echo "export GROUP=kurumai" >> $BASH_ENV
            echo "export COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            echo "export TAG=${CIRCLE_TAG}" >> $BASH_ENV
            echo "export REPO=front-end" >> $BASH_ENV
            env
      - run:
          name: make test-image deps
          command: |
            source $BASH_ENV
            make test-image deps
      - run: npm install
      #- run: make test

      - run:
          name:
          command: |
            docker login -u "${DOCKER_USER}" -p "${DOCKER_PASS}";
            docker build -t ${GROUP}/front-end:${COMMIT} .
          #  ./scripts/push.sh

workflows:
  test_and_deploy:
    jobs:
      - test
