version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: set env
          command: |
            echo "export GROUP=weaveworksdemos" >> $BASH_ENV
            echo "export COMMIT=${CIRCLE_SHA1}" >> $BASH_ENV
            echo "export TAG=${CIRCLE_TAG}" >> $BASH_ENV
            echo "export REPO=front-end" >> $BASH_ENV
            env
      - run: make test-image deps
      #- node/install-packages
      - run: npm install
      - run: make test

workflows:
  test_and_deploy:
    jobs:
      - test
      