version: 2.1

orbs:
  node: circleci/node@3.0.1

jobs:
  test:
    machine:
      docker_layer_caching: true
      image: ubuntu-1604:201903-01
    environment:
      GROUP: weaveworksdemos
      COMMIT: ${CIRCLE_SHA1}
      TAG: ${CIRCLE_TAG}
      REPO: front-end
    steps:
      - checkout
      - run: make test-image deps
      #- node/install-packages
      - run: npm install
      - run: make test

workflows:
  test_and_deploy:
    jobs:
      - test